# Generated by Django 4.1.5 on 2023-05-10 03:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField(default=datetime.datetime.now)),
                ('time_joined', models.TimeField(default=datetime.datetime.now)),
                ('ip_address', models.CharField(max_length=50)),
                ('browser', models.CharField(blank=True, max_length=60, null=True)),
                ('device', models.CharField(blank=True, max_length=90, null=True)),
                ('type', models.CharField(choices=[('success', 'Éxitoso'), ('failed', 'Fallido')], default='success', max_length=15)),
            ],
            options={
                'verbose_name': 'Acceso de Usuario',
                'verbose_name_plural': 'Accesos de Usuarios',
                'ordering': ['id'],
                'permissions': (('view_access_users', 'Can view Accesos de Usuarios'), ('delete_access_users', 'Can delete Accesos de Usuarios')),
                'default_permissions': (),
            },
        ),
    ]
